#nullable enable
using System.Globalization;
using AAEmu.GodotViewer.Lua;
using AAEmu.GodotViewer.Ui.X2.Scripting.World;

namespace AAEmu.GodotViewer.Ui.X2.Scripting.Api;

/// <summary>Immutable state used by the world-facing x2ui API families.</summary>
public sealed record X2WorldState
{
    public int WorldId { get; init; }
    public string WorldName { get; init; } = "";
    public int AuthId { get; init; }
    public int CharacterCount { get; init; }
    public int DefaultCharactersPerWorld { get; init; } = 6;
    public int DefaultCharactersPerAccount { get; init; } = 12;
    public int ExpandableCharacters { get; init; }
    public int ExpandedCharacters { get; init; }
    public int ZoneId { get; init; }
    /// <summary>zones.group_id of the current zone (X2Unit:GetCurrentZoneGroup; 0 when unknown).</summary>
    public int ZoneGroupId { get; init; }
    public string ZoneName { get; init; } = "";
    public string SubZoneName { get; init; } = "";
    public string ZoneFaction { get; init; } = "";
    public IReadOnlyList<X2ZoneInfo> Zones { get; init; } = [];
}

/// <summary>A world/zone entry. Coordinates and conflict state are live server state.</summary>
public sealed record X2ZoneInfo(int Id, string Name, int WorldId = 0, int ConflictState = 0,
    double ConflictRemainSeconds = 0, bool IsConflictZone = false, bool IsFestivalZone = false,
    bool IsInstanceZone = false, string FestivalName = "", bool IsNuiaProtectedZone = false,
    bool IsHariharaProtectedZone = false, bool IsPeaceZone = false, bool IsSiegeZone = false);

/// <summary>A saved, return, favorite, or instance portal row.</summary>
public sealed record X2PortalInfo(string PortalType, long Id, string Name, int ZoneId = 0,
    string ZoneName = "", string Memo = "", bool Favorite = false, int Category = 0,
    double X = 0, double Y = 0, double Z = 0);

/// <summary>The house currently selected by an interaction, or null outside housing interaction.</summary>
public sealed record X2HouseInfo(long Id, int Type, string Name, string OwnerName, string ZoneName,
    bool IsMine, bool UnderConstruction, bool Rotatable, int Permission = 0,
    double BaseProgress = 0, double RemainingProgress = 0, bool AllowRecover = false);

/// <summary>Current instance state; null when the character is not in an instance.</summary>
public sealed record X2InstanceState(bool IsInInstantGame, int InstanceType = 0, string Name = "",
    int Round = 0, int TotalRounds = 0, double RoundSecondsLeft = 0, bool IsGlobalField = false,
    string ProgressState = "", double ProgressSecondsLeft = 0, double ExitSecondsLeft = 0,
    int TeamCount = 0, int LeftTimeCount = 0, int StackCount = 0,
    IReadOnlyList<X2InstancePoint> PointInfo = null!);

/// <summary>A name/value row shown by an instance objective scoreboard.</summary>
public sealed record X2InstancePoint(string Name, double Value, double Maximum = 0);

/// <summary>Currently controlled mount, vehicle, or ship; null when none is summoned.</summary>
public sealed record X2VehicleState(uint UnitId, string Name, bool IsShip, double Speed,
    double TurnSpeed, double Hp = 0, double MaxHp = 0, int CustomizingType = 0,
    uint TemplateId = 0, string Kind = "", int Gear = 0, bool Handbrake = false,
    bool TractionControl = false, double X = 0, double Y = 0, double Z = 0);

/// <summary>
/// A recursively typed API table. Values may be null, string, bool, a numeric primitive, another X2ApiTable,
/// or a read-only list of those values. Field names are the exact keys consumed by x2ui.
/// </summary>
public sealed record X2ApiTable(IReadOnlyDictionary<string, object?> Fields, IReadOnlyList<object?>? Rows = null)
{
    public static X2ApiTable Empty { get; } = new(new Dictionary<string, object?>());
}

/// <summary>
/// One native API result. <see cref="Single"/> may be a primitive, X2ApiTable, or read-only list.
/// <see cref="Multiple"/> preserves ordered Lua multiple returns and takes precedence when non-null.
/// </summary>
public sealed record X2ApiResult(object? Single = null, IReadOnlyList<object?>? Multiple = null)
{
    public static X2ApiResult Scalar(object? value) => new(value);
    public static X2ApiResult Table(X2ApiTable value) => new(value);
    public static X2ApiResult Multi(params object?[] values) => new(null, values);
}

/// <summary>
/// Table results for one API family. Keys are a method name, or method plus invariant arguments separated by '|'
/// (for example "GetZoneStateInfoByZoneId|123"). This preserves argument-specific server snapshots.
/// </summary>
public sealed record X2ApiFamilySnapshot(IReadOnlyDictionary<string, X2ApiResult> Results)
{
    public static X2ApiFamilySnapshot Empty { get; } = new(new Dictionary<string, X2ApiResult>());
}

/// <summary>A command generated by a Lua API call. Arguments retain Lua's one-based indices and primitive values.</summary>
public sealed record X2WorldCommand(string Table, string Method, IReadOnlyList<object?> Arguments);

/// <summary>Synchronous result for commands whose native binding reports acceptance or a numeric status.</summary>
public sealed record X2WorldCommandResult(bool Accepted = false, double Number = 0, string Text = "");

/// <summary>
/// Live state and requests required by map, world, portal, time, housing, dominion, resident,
/// instance, battlefield, siege-weapon, decal, and interaction APIs.
/// </summary>
public interface IX2WorldData
{
    X2WorldState World { get; }
    DateTimeOffset ServerTime { get; }
    DateTimeOffset LocalTime { get; }
    /// <summary>Monotonic UI time in milliseconds.</summary>
    long UiMilliseconds { get; }
    /// <summary>ArcheAge world clock, in hours [0,24).</summary>
    double GameHour { get; }
    IReadOnlyList<X2PortalInfo> Portals { get; }
    IReadOnlyList<X2PortalInfo> ReturnPoints { get; }
    IReadOnlyList<X2PortalInfo> InstancePortals { get; }
    X2HouseInfo? CurrentHouse { get; }
    X2InstanceState? CurrentInstance { get; }
    X2VehicleState? CurrentVehicle { get; }
    /// <summary>Map checklists, alarms, zone state, and faction competition tables.</summary>
    X2ApiFamilySnapshot Map { get; }
    /// <summary>Non-login X2World service, terms, zone, and account query results.</summary>
    X2ApiFamilySnapshot WorldApi { get; }
    /// <summary>Portal queries not represented by the strongly typed portal lists.</summary>
    X2ApiFamilySnapshot Warp { get; }
    /// <summary>Housing tax, construction, sale, UCC, rebuilding, and item tables.</summary>
    X2ApiFamilySnapshot Housing { get; }
    /// <summary>Dominion ownership, siege periods, scores, rewards, and timer tables.</summary>
    X2ApiFamilySnapshot Dominion { get; }
    /// <summary>Resident board, member, zone, reward, and housing-trade tables.</summary>
    X2ApiFamilySnapshot Resident { get; }
    /// <summary>Dungeon round, playing, and entrance tables.</summary>
    X2ApiFamilySnapshot Indun { get; }
    /// <summary>Battlefield entrance, progress, score, faction, member, reward, and banner tables.</summary>
    X2ApiFamilySnapshot BattleField { get; }
    /// <summary>Instance summary and faction-point tables.</summary>
    X2ApiFamilySnapshot InstanceData { get; }
    /// <summary>Mounted weapon, vehicle, ship, and equipment-slot tables.</summary>
    X2ApiFamilySnapshot SiegeWeapon { get; }
    /// <summary>Quest guide and target-decal capability query results.</summary>
    X2ApiFamilySnapshot Decal { get; }
    /// <summary>NPC interaction query results.</summary>
    X2ApiFamilySnapshot Interaction { get; }
    string InteractionSkillIconPath { get; }
    /// <summary>Forwards a server request or renderer-side command. State changes only after host/network confirmation.</summary>
    X2WorldCommandResult Execute(X2WorldCommand command);
}

/// <summary>Offline/fresh-character world state.</summary>
public class NullWorldData : IX2WorldData
{
    public static readonly NullWorldData Instance = new();
    private readonly long _started = Environment.TickCount64;
    public virtual X2WorldState World { get; } = new();
    public virtual DateTimeOffset ServerTime => DateTimeOffset.UtcNow;
    public virtual DateTimeOffset LocalTime => DateTimeOffset.Now;
    public virtual long UiMilliseconds => Environment.TickCount64 - _started;
    public virtual double GameHour => LocalTime.TimeOfDay.TotalHours;
    public virtual IReadOnlyList<X2PortalInfo> Portals => [];
    public virtual IReadOnlyList<X2PortalInfo> ReturnPoints => [];
    public virtual IReadOnlyList<X2PortalInfo> InstancePortals => [];
    public virtual X2HouseInfo? CurrentHouse => null;
    public virtual X2InstanceState? CurrentInstance => null;
    public virtual X2VehicleState? CurrentVehicle => null;
    public virtual X2ApiFamilySnapshot Map => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot WorldApi => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot Warp => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot Housing => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot Dominion => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot Resident => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot Indun => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot BattleField => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot InstanceData => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot SiegeWeapon => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot Decal => X2ApiFamilySnapshot.Empty;
    public virtual X2ApiFamilySnapshot Interaction => X2ApiFamilySnapshot.Empty;
    public virtual string InteractionSkillIconPath => "";
    public virtual X2WorldCommandResult Execute(X2WorldCommand command) => new();
}

/// <summary>
/// Registers the World-family methods from the 10.0.2.13 generated API metadata.
/// X2World methods owned by X2Engine are deliberately retained because they carry the active login/world-selection session.
/// </summary>
public static class X2WorldApi
{
    private readonly record struct Binding(string Name, char Kind);

    public static void Install(X2LuaHost host, X2GameContext context, IX2WorldData data)
    {
        ArgumentNullException.ThrowIfNull(host);
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(data);

        foreach (var (table, bindings) in All)
            foreach (var binding in bindings)
            {
                if (table == "X2World" && EngineOwnedWorldMethods.Contains(binding.Name))
                    continue;
                var capturedTable = table;
                var captured = binding;
                host.Define(capturedTable, captured.Name,
                    args => Invoke(capturedTable, captured, args, context, data));
            }
    }

    private static object? Invoke(string table, Binding binding, LuaArgs a, X2GameContext context, IX2WorldData data)
    {
        var key = table + "." + binding.Name;
        if (Snapshot(data, table) is { } family && Find(family, binding.Name, a) is { } capturedResult)
            return ToLuaResult(capturedResult);
        switch (key)
        {
            case "X2Time.GetUiMsec": return (double)data.UiMilliseconds;
            case "X2Time.GetLocalTime": return Epoch(data.LocalTime).ToString(CultureInfo.InvariantCulture);
            case "X2Time.GetLocalDate": return Date(data.LocalTime);
            case "X2Time.GetServerTime": return Date(data.ServerTime);
            case "X2Time.GetGameTime":
                var h24 = ((data.GameHour % 24) + 24) % 24;
                return new LuaMulti(h24 < 12, h24 < 12 ? Math.Floor(h24) : Math.Floor(h24) - 12, (h24 % 1) * 60);
            case "X2Time.CompareTime":
                var l = ParseTime(a[0]); var r = ParseTime(a[1]);
                return l == r ? 0d : l < r ? -1d : 1d;
            case "X2Time.TimeToDate": return Date(DateTimeOffset.FromUnixTimeSeconds(ParseTime(a[0])).ToLocalTime());
            case "X2Time.PeriodToDate": return Period(a.Num(0));
            case "X2Time.PeriodTimeToDate": return Period(ParseTime(a[1]) - ParseTime(a[0]));
            case "X2Time.DateToTimeString":
                return new DateTimeOffset(a.Int(0), Math.Clamp(a.Int(1), 1, 12), Math.Clamp(a.Int(2), 1, 28),
                    Math.Clamp(a.Int(3), 0, 23), Math.Clamp(a.Int(4), 0, 59), Math.Clamp(a.Int(5), 0, 59), TimeSpan.Zero)
                    .ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture);

            case "X2World.GetAuthId": return (double)data.World.AuthId;
            case "X2World.GetCurrentWorldName": return data.World.WorldName;
            case "X2World.GetCurrentWorldInfo": return WorldEntry(data.World);
            case "X2World.GetWorldInfo": return Array(data.World.WorldId == 0 ? [] : [WorldEntry(data.World)]);
            case "X2World.GetCharactersInfoPerWorld": return new LuaTable();
            case "X2World.GetCharactersCountPerWorld": return a.Int(0) == data.World.WorldId ? (double)data.World.CharacterCount : 0d;
            case "X2World.GetCharactersCountPerAccount": return (double)data.World.CharacterCount;
            case "X2World.GetCharactersDefaultLimitPerWorld": return (double)data.World.DefaultCharactersPerWorld;
            case "X2World.GetCharactersDefaultLimitPerAccount": return (double)data.World.DefaultCharactersPerAccount;
            case "X2World.GetCharacterExpandableLimit": return (double)data.World.ExpandableCharacters;
            case "X2World.GetExpandedCharacterCount": return (double)data.World.ExpandedCharacters;
            case "X2World.GetExpandedCharacterRemainCount": return (double)Math.Max(0, data.World.ExpandableCharacters - data.World.ExpandedCharacters);
            case "X2World.GetRemainChracterCountPerAccout": return (double)Math.Max(0, data.World.DefaultCharactersPerAccount - data.World.CharacterCount);
            case "X2World.GetZoneCount": return (double)data.World.Zones.Count;
            case "X2World.GetZoneInfo": return ZoneAt(data.World.Zones, a.Int(0));
            case "X2World.GetZoneName": return ZoneAt(data.World.Zones, a.Int(0))?["name"] ?? "";
            case "X2World.GetZoneText": return data.World.ZoneName;
            case "X2World.GetSubZoneText": return data.World.ZoneId != 0 && string.IsNullOrEmpty(data.World.SubZoneName)
                ? null : data.World.SubZoneName;
            case "X2World.GetZoneFaction": return data.World.ZoneFaction;
            case "X2World.IsWorld": return a.Int(0) == data.World.WorldId;
            case "X2World.IsDivision": return false;
            case "X2World.IsUsingAutoLogin":
            case "X2World.IsPreSelectCharacterPeriod":
            case "X2World.IsPreSelectCharacterPeriodForPcbang":
            case "X2World.IsPreSelectCharacterPeriodForPremium":
            case "X2World.ForbidCharCreation":
            case "X2World.CanPreSelectCharacter":
            case "X2World.IsB2PService": return false;
            case "X2World.LevelCount": return 0d;
            case "X2World.LevelName": return "";

            case "X2Map.GetZoneListByWorldId":
                return Array(data.World.Zones.Where(z => z.WorldId == 0 || z.WorldId == a.Int(0)).Select(ZoneEntry));
            case "X2Map.GetZoneStateInfoByZoneId":
                // the scripts pass X2Unit:GetCurrentZoneGroup() (a zones.group_id); our zone list is keyed by zone key
                var zoneId = a.Int(0) == 0 ? data.World.ZoneId : a.Int(0);
                var zone = data.World.Zones.FirstOrDefault(z => z.Id == zoneId) ??
                    (zoneId != 0 && zoneId == data.World.ZoneGroupId ? data.World.Zones.FirstOrDefault(z => z.Id == data.World.ZoneId) : null);
                return zone is null ? null : ZoneState(zone, zone.Id == data.World.ZoneId);
            case "X2Map.GetZoneStateTextInfo": return new LuaTable { ["stateTitle"] = "", ["tooltipTitle"] = "" };
            case "X2Map.GetCheckList": return Array(Online.X2MapIconCatalog.CheckList(a.Int(0)).Select(i => (object?)(double)i));
            case "X2Map.GetMapIconText": return Online.X2MapIconCatalog.IconText(a.Int(0));
            case "X2Map.GetMapIconCoord": return Online.X2MapIconCatalog.IconCoord(a.Int(0));
            case "X2Map.IsCheckedMapFilter": return Online.X2MapIconCatalog.IsChecked(a.Int(0));
            case "X2Map.GetZoneFactionCompetitionRemainTime": return 0d;

            case "X2Warp.GetPortalList": return PortalArray(Filter(data.Portals, a.Str(0), a.Int(1)));
            case "X2Warp.GetFavoritePortalList": return PortalArray(Filter(data.Portals.Where(p => p.Favorite), a.Str(0), a.Int(1)));
            case "X2Warp.GetReturnList": return PortalArray(Filter(data.ReturnPoints, a.Str(0), a.Int(1)));
            case "X2Warp.GetIndunPortalList": return PortalArray(Filter(data.InstancePortals, a.Str(0), 0));
            case "X2Warp.GetFavoritePortalCountInfos":
                return new LuaMulti((double)data.Portals.Count(p => p.Favorite), (double)data.Portals.Count);
            case "X2Warp.GetBoundPortalId": return data.ReturnPoints.FirstOrDefault()?.Id.ToString(CultureInfo.InvariantCulture) ?? "";

            case "X2House.GetHouseId": return (double)(data.CurrentHouse?.Id ?? 0);
            case "X2House.GetHouseType": return (double)(data.CurrentHouse?.Type ?? 0);
            case "X2House.GetHouseName": return data.CurrentHouse?.Name ?? "";
            case "X2House.GetHouseOwnerName": return data.CurrentHouse?.OwnerName ?? "";
            case "X2House.GetHouseZoneName": return data.CurrentHouse?.ZoneName ?? "";
            case "X2House.IsMyHouse": return data.CurrentHouse?.IsMine ?? false;
            case "X2House.IsHouseUnderConstruction": return data.CurrentHouse?.UnderConstruction ?? false;
            case "X2House.IsHouseRotatable": return data.CurrentHouse?.Rotatable ?? false;
            case "X2House.GetHousePermission": return (double)(data.CurrentHouse?.Permission ?? 0);
            case "X2House.GetHouseBaseProgress": return data.CurrentHouse?.BaseProgress ?? 0;
            case "X2House.GetHouseRemainProgress": return data.CurrentHouse?.RemainingProgress ?? 0;
            case "X2House.GetHouseAllowRecover": return data.CurrentHouse?.AllowRecover ?? false;

            case "X2Indun.IsEntranceIndunMatch":
            case "X2BattleField.IsInInstantGame": return data.CurrentInstance?.IsInInstantGame ?? false;
            case "X2BattleField.IsInGlobalField": return data.CurrentInstance?.IsGlobalField ?? false;
            case "X2Indun.GetTotalRound": return (double)(data.CurrentInstance?.TotalRounds ?? 0);
            case "X2Indun.GetRoundLeftTime": return data.CurrentInstance?.RoundSecondsLeft ?? 0;
            case "X2Indun.GetIndunPlayingInfo": return data.CurrentInstance is { } inst ? Instance(inst) : null;
            case "X2Indun.GetRoundInfo": return data.CurrentInstance is { } round ? new LuaTable { ["currentRound"] = (double)round.Round } : null;
            case "X2BattleField.GetInstanceName": return data.CurrentInstance?.Name ?? "";
            case "X2BattleField.GetProgressTimeInfo": return data.CurrentInstance is { } progress ? ProgressTime(progress) : null;
            case "X2Instance.GetInstanceSummaryInfo": return data.CurrentInstance is { } summary
                ? new LuaTable { ["type"] = (double)summary.InstanceType, ["isStarted"] = summary.ProgressState == "STARTED" }
                : null;
            case "X2Instance.GetPointInfo": return data.CurrentInstance is { } points ? PointArray(points.PointInfo ?? []) : null;

            case "X2SiegeWeapon.GetSiegeWeaponSpeed": return data.CurrentVehicle?.Speed ?? 0;
            case "X2SiegeWeapon.GetSiegeWeaponTurnSpeed": return data.CurrentVehicle?.TurnSpeed ?? 0;
            case "X2SiegeWeapon.GetSlaveCustomizingType": return (double)(data.CurrentVehicle?.CustomizingType ?? 0);
            case "X2SiegeWeapon.IsSlaveShip": return data.CurrentVehicle?.IsShip ?? false;
            case "X2SiegeWeapon.GetVehicleInfo": return data.CurrentVehicle is { IsShip: false } v ? Vehicle(v) : null;
            case "X2SiegeWeapon.GetShipInfo": return data.CurrentVehicle is { IsShip: true } ship ? Vehicle(ship) : null;
            case "X2SiegeWeapon.GetMountedSiegeWeaponInfo": return data.CurrentVehicle is { } mounted ? Vehicle(mounted) : null;
            case "X2Interaction.GetInteractionSkillIconPath": return data.InteractionSkillIconPath;
            case "X2Decal.GetMaxDecalCount": return 11d;
            // The quest notifier gates its navigation icon and distance behind these checks.
            // A positive quest type denotes an active quest supplied by its journal list.
            case "X2Decal.CanMakeDirectionGuide":
            case "X2Decal.CanMakeGuidedDecal": return a.Num(0) > 0;
        }

        if (IsCommand(binding.Name))
        {
            if (table == "X2Map" && binding.Name == "SetMapFilter")
            {
                Online.X2MapIconCatalog.SetChecked(a.Int(0), a.Bool(1));
                return null;
            }
            if (table == "X2Map" && binding.Name == "SetShowFilter")
            {
                Online.X2MapIconCatalog.SetFolder(a.Int(0), a.Bool(1));
                return null;
            }
            var result = data.Execute(new X2WorldCommand(table, binding.Name, a.Values.ToArray()));
            return binding.Kind switch { 'b' => result.Accepted, 'n' => result.Number, 's' => result.Text, _ => null };
        }

        // Empty state matches unavailable features on a fresh character and keeps optional windows closed.
        return binding.Kind switch { 'n' => 0d, 'b' => false, 's' => "", 't' => new LuaTable(), _ => null };
    }

    private static bool IsCommand(string name) => name.StartsWith("Set", StringComparison.Ordinal) ||
        name.StartsWith("Request", StringComparison.Ordinal) || name.StartsWith("Cancel", StringComparison.Ordinal) ||
        name.StartsWith("Open", StringComparison.Ordinal) || name.StartsWith("Delete", StringComparison.Ordinal) ||
        name.StartsWith("Rename", StringComparison.Ordinal) || name.StartsWith("Save", StringComparison.Ordinal) ||
        name.StartsWith("Remove", StringComparison.Ordinal) || name.StartsWith("Update", StringComparison.Ordinal) ||
        name.StartsWith("Clear", StringComparison.Ordinal) || name.StartsWith("Buy", StringComparison.Ordinal) ||
        name.StartsWith("Demolish", StringComparison.Ordinal) || name.StartsWith("Enter", StringComparison.Ordinal) ||
        name.StartsWith("Leave", StringComparison.Ordinal) || name.StartsWith("Exit", StringComparison.Ordinal) ||
        name.StartsWith("Preview", StringComparison.Ordinal) || name.StartsWith("Rotate", StringComparison.Ordinal) ||
        name.StartsWith("Start", StringComparison.Ordinal) || name.StartsWith("Use", StringComparison.Ordinal) ||
        name.StartsWith("Change", StringComparison.Ordinal) || name.StartsWith("Fire", StringComparison.Ordinal) ||
        name.StartsWith("Refresh", StringComparison.Ordinal) || name.StartsWith("Ask", StringComparison.Ordinal) ||
        name.StartsWith("Pick", StringComparison.Ordinal) || name.StartsWith("Toggle", StringComparison.Ordinal) ||
        name.StartsWith("Off", StringComparison.Ordinal) || name.StartsWith("End", StringComparison.Ordinal) ||
        name.StartsWith("LookAhead", StringComparison.Ordinal) || name.StartsWith("Next", StringComparison.Ordinal) ||
        name.StartsWith("Prev", StringComparison.Ordinal) || name.StartsWith("Prepay", StringComparison.Ordinal);

    private static X2ApiFamilySnapshot? Snapshot(IX2WorldData data, string table) => table switch
    {
        "X2Map" => data.Map, "X2World" => data.WorldApi, "X2Warp" => data.Warp,
        "X2House" => data.Housing, "X2Dominion" => data.Dominion,
        "X2Resident" => data.Resident, "X2Indun" => data.Indun, "X2BattleField" => data.BattleField,
        "X2Instance" => data.InstanceData, "X2SiegeWeapon" => data.SiegeWeapon,
        "X2Decal" => data.Decal, "X2Interaction" => data.Interaction, _ => null
    };

    private static X2ApiResult? Find(X2ApiFamilySnapshot family, string method, LuaArgs args)
    {
        if (args.Count > 0)
        {
            var exact = method + "|" + string.Join("|", args.Values.Select(v => v switch
            {
                null => "", double d => d.ToString(CultureInfo.InvariantCulture), bool b => b ? "true" : "false",
                _ => v.ToString() ?? ""
            }));
            if (family.Results.TryGetValue(exact, out var result)) return result;
        }
        return family.Results.TryGetValue(method, out var fallback) ? fallback : null;
    }

    private static object? ToLuaResult(X2ApiResult result) => result.Multiple is { } values
        ? new LuaMulti(values.Select(ToLuaValue).ToArray())
        : ToLuaValue(result.Single);

    private static LuaTable ToLua(X2ApiTable value)
    {
        var table = new LuaTable();
        foreach (var (key, item) in value.Fields) table[key] = ToLuaValue(item);
        if (value.Rows is { } rows)
        {
            double index = 1;
            foreach (var item in rows) table[index++] = ToLuaValue(item);
        }
        return table;
    }

    private static object? ToLuaValue(object? value) => value switch
    {
        X2ApiTable table => ToLua(table),
        IEnumerable<X2ApiTable> tables => Array(tables.Select(ToLua)),
        IEnumerable<object?> values when value is not string => Array(values.Select(ToLuaValue)),
        _ => value
    };

    private static long ParseTime(object? value) => value switch
    {
        double d => (long)d,
        string s when long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var n) => n,
        LuaTable t when t.TryGetValue("year", out var y) => FromDate(t, y),
        _ => 0
    };

    private static long FromDate(LuaTable t, object? year) => new DateTimeOffset(
        Convert.ToInt32(year, CultureInfo.InvariantCulture), GetInt(t, "month", 1), GetInt(t, "day", 1),
        GetInt(t, "hour"), GetInt(t, "minute"), GetInt(t, "second"), TimeSpan.Zero).ToUnixTimeSeconds();
    private static int GetInt(LuaTable t, string key, int fallback = 0) =>
        t.TryGetValue(key, out var v) ? Convert.ToInt32(v, CultureInfo.InvariantCulture) : fallback;
    private static long Epoch(DateTimeOffset value) => value.ToUnixTimeSeconds();
    private static LuaTable Date(DateTimeOffset d) => new()
    {
        ["year"] = (double)d.Year, ["month"] = (double)d.Month, ["day"] = (double)d.Day,
        ["hour"] = (double)d.Hour, ["minute"] = (double)d.Minute, ["second"] = (double)d.Second,
        ["dayOfWeek"] = (double)d.DayOfWeek
    };
    private static LuaTable Period(double seconds)
    {
        seconds = Math.Max(0, seconds);
        var days = Math.Floor(seconds / 86400); seconds -= days * 86400;
        var hours = Math.Floor(seconds / 3600); seconds -= hours * 3600;
        var minutes = Math.Floor(seconds / 60); seconds -= minutes * 60;
        return new LuaTable { ["year"] = 0d, ["month"] = 0d, ["day"] = days, ["hour"] = hours,
            ["minute"] = minutes, ["second"] = Math.Floor(seconds) };
    }
    private static LuaTable WorldEntry(X2WorldState w) => new()
    {
        ["id"] = (double)w.WorldId, ["name"] = w.WorldName, ["worldId"] = (double)w.WorldId,
        ["isWorld"] = true, ["isUp"] = true, ["load"] = 0d
    };
    private static LuaTable? ZoneAt(IReadOnlyList<X2ZoneInfo> zones, int oneBased) =>
        oneBased > 0 && oneBased <= zones.Count ? ZoneEntry(zones[oneBased - 1]) : null;
    private static LuaTable ZoneEntry(X2ZoneInfo z) => new()
    { ["id"] = (double)z.Id, ["zoneId"] = (double)z.Id, ["name"] = z.Name, ["worldId"] = (double)z.WorldId };
    private static LuaTable ZoneState(X2ZoneInfo z, bool current) => new()
    {
        ["zoneId"] = (double)z.Id, ["zoneName"] = z.Name, ["conflictState"] = (double)z.ConflictState,
        ["remainTime"] = z.ConflictRemainSeconds, ["isConflictZone"] = z.IsConflictZone,
        ["isFestivalZone"] = z.IsFestivalZone, ["isInstanceZone"] = z.IsInstanceZone,
        ["isCurrentZone"] = current, ["festivalName"] = z.FestivalName,
        ["isNuiaProtectedZone"] = z.IsNuiaProtectedZone,
        ["isHariharaProtectedZone"] = z.IsHariharaProtectedZone,
        ["isPeaceZone"] = z.IsPeaceZone, ["isSiegeZone"] = z.IsSiegeZone
    };
    private static IEnumerable<X2PortalInfo> Filter(IEnumerable<X2PortalInfo> source, string? search, int category) =>
        source.Where(p => (string.IsNullOrWhiteSpace(search) || p.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase)) &&
                          (category == 0 || p.Category == category));
    private static LuaTable PortalArray(IEnumerable<X2PortalInfo> portals) => Array(portals.Select(p => new LuaTable
    {
        ["portalType"] = p.PortalType, ["portalId"] = p.Id.ToString(CultureInfo.InvariantCulture), ["id"] = p.Id.ToString(CultureInfo.InvariantCulture),
        ["name"] = p.Name, ["zoneId"] = (double)p.ZoneId, ["zoneName"] = p.ZoneName, ["memo"] = p.Memo,
        ["isFavorite"] = p.Favorite, ["category"] = (double)p.Category, ["x"] = p.X, ["y"] = p.Y, ["z"] = p.Z
    }));
    private static LuaTable Instance(X2InstanceState i) => new()
    { ["instanceType"] = (double)i.InstanceType, ["name"] = i.Name, ["round"] = (double)i.Round,
      ["totalRound"] = (double)i.TotalRounds, ["leftTime"] = i.RoundSecondsLeft,
      ["leftTimeCount"] = (double)i.LeftTimeCount, ["stackCount"] = (double)i.StackCount,
      ["pointInfo"] = PointArray(i.PointInfo ?? []) };
    private static LuaTable ProgressTime(X2InstanceState i) => new()
    { ["state"] = i.ProgressState, ["remainTime"] = i.ProgressSecondsLeft,
      ["outWaitTime"] = i.ExitSecondsLeft, ["teamCount"] = (double)i.TeamCount };
    private static LuaTable PointArray(IEnumerable<X2InstancePoint> points) => Array(points.Select(p => new LuaTable
    { ["name"] = p.Name, ["point"] = p.Value, ["value"] = p.Value, ["maxPoint"] = p.Maximum }));
    private static LuaTable Vehicle(X2VehicleState v) => new()
    { ["unitId"] = v.UnitId.ToString(CultureInfo.InvariantCulture), ["name"] = v.Name, ["isShip"] = v.IsShip, ["speed"] = v.Speed,
      ["turnSpeed"] = v.TurnSpeed, ["hp"] = v.Hp, ["maxHp"] = v.MaxHp,
      ["health"] = v.Hp, ["maxHealth"] = v.MaxHp, ["customizingType"] = (double)v.CustomizingType,
      ["templateId"] = (double)v.TemplateId, ["kind"] = v.Kind, ["gear"] = (double)v.Gear,
      ["handbrake"] = v.Handbrake, ["tractionCtrl"] = v.TractionControl,
      ["x"] = v.X, ["y"] = v.Y, ["z"] = v.Z,
      ["siege_incoming_dmg_mul"] = 0d, ["mass"] = 0d, ["collisionDmg"] = 0d,
      ["collisionAmr"] = 0d, ["now"] = 0d, ["max"] = 0d, ["sinkingMax"] = 0d };
    private static LuaTable Array(IEnumerable<object?> values)
    {
        var t = new LuaTable(); double i = 1;
        foreach (var value in values) t[i++] = value;
        return t;
    }

    private static Binding[] B(string spec) => spec.Split(' ', StringSplitOptions.RemoveEmptyEntries)
        .Select(s => { var p = s.Split(':'); return new Binding(p[0], p.Length == 1 ? '\0' : p[1][0]); }).ToArray();

    // X2LoginSession installs X2Engine first. Re-registering these names would replace closures over its selected world,
    // character list, refresh callback, and enter/leave actions with the in-game data adapter.
    private static readonly HashSet<string> EngineOwnedWorldMethods = new(StringComparer.Ordinal)
    {
        "IsUsingAutoLogin", "GetWorldInfo", "GetServerInfoTexts", "GetAuthId",
        "GetCharactersCountPerWorld", "GetCharactersCountPerAccount", "GetCharactersDefaultLimitPerWorld",
        "GetCharactersDefaultLimitPerAccount", "GetCharacterExpandableLimit", "GetRemainChracterCountPerAccout",
        "GetExpandedCharacterRemainCount", "GetTmpMaxCharSlot", "RequestWorldListRefresh", "EnterWorld",
        "GetCurrentWorldName", "GetCurrentWorldInfo", "LeaveWorld", "IsPreSelectCharacterPeriod",
        "ForbidCharCreation", "CanPreSelectCharacter"
    };

    private static readonly IReadOnlyDictionary<string, Binding[]> All = new Dictionary<string, Binding[]>(StringComparer.Ordinal)
    {
        ["X2Map"] = B("GetCheckList:t GetDefault:t GetMapIconCoord:s GetMapIconText:s GetMySlaveHealth GetTelescopeUnitHealth GetTowerDefAlarmInfo:t GetZoneDoodadText GetZoneFactionCompetitionInfo:t GetZoneFactionCompetitionRemainTime:n GetZoneGroupOfCity:n GetZoneListByWorldId:t GetZoneStateInfoByZoneId:t GetZoneStateTextInfo:t IsCheckedMapFilter:b RemoveAllNotifyQuestInfo RemoveNotifyQuestInfo SetMapFilter SetNotifyAreaColors SetNotifyAreaCoords SetNotifyCoords SetSafeAreaTextureSettings SetShipCoords SetShowFilter UpdateNotifyQuestInfo"),
        ["X2World"] = B("CanExitArchemall:b CanPreSelectCharacter:b CancelLeaveWorld:b EnterWorld ExitArchemall ForbidCharCreation:b GetAuthId:n GetCharacterExpandableLimit:n GetCharactersCountPerAccount:n GetCharactersCountPerWorld:n GetCharactersDefaultLimitPerAccount:n GetCharactersDefaultLimitPerWorld:n GetCharactersInfoPerWorld:t GetCurrentWorldInfo:t GetCurrentWorldName:s GetExpandedCharacterCount:n GetExpandedCharacterRemainCount:n GetRemainChracterCountPerAccout:n GetServerInfoTexts GetSubZoneText:s GetTermsText:t GetTmpMaxCharSlot:n GetWorldInfo:t GetZoneCount:n GetZoneFaction GetZoneInfo:t GetZoneName:s GetZoneText:s IsB2PService:b IsDivision:b IsPreSelectCharacterPeriod:b IsPreSelectCharacterPeriodForPcbang:b IsPreSelectCharacterPeriodForPremium:b IsUsingAutoLogin:b IsWorld:b LeaveWorld:b LevelCount:n LevelName:s PrivacyPolicyAgree:b RequestWorldListRefresh"),
        ["X2Warp"] = B("DeletePortal EndPortalInteraction GetBoundPortalId:s GetFavoritePortalCountInfos:t GetFavoritePortalList:t GetIndunPortalList:t GetPortalList:t GetReturnList:t IsTeleporterNpc:b OpenIndunPortal OpenPortal RenamePortal SavePortal SetFavoritePortal"),
        ["X2Time"] = B("CompareTime:n DateToTimeString GetGameTime GetLocalDate:t GetLocalTime:s GetServerTime:t GetUiMsec:n PeriodTimeToDate:t PeriodToDate:t TimeToDate:t"),
        ["X2House"] = B("BuyHouse CalcHouseBuildTotalPayStr CanPackageDemolish:b CanRebuild:b CanUseHousingUcc:b CancelHouseForSale CancelRebuild ClearUccItemSlot CountTaxItemForTax CountTaxItemInBag:n Demolish EnterUccApply EnterUccRemove GetActabilityDecoCount:n GetCurrencyForHouseSale:n GetCurrencyForTax:n GetCurrentHousingItemType:n GetCurrentHousingTaxInfo:t GetDecoActabilityByType GetDecoActabilityLimitGroup:t GetDecoActabilityPoint:n GetDemolishSealCount GetGuardTowerStepInfo GetHouseAllowRecover:b GetHouseBaseProgress:n GetHouseConstructionStepInfo:t GetHouseDecoCount GetHouseId:n GetHouseName:s GetHouseOwnerName:s GetHousePermission GetHouseRemainProgress:n GetHouseSaleInfo:t GetHouseSaleItemInfo:t GetHouseSaleTaxInfo:n GetHouseType:n GetHouseZoneName GetHousingModelConstructionInfo:t GetHousingModelName:s GetHousingRebuildingBaseInfo:t GetHousingRebuildingMaterialInfo:t GetHousingRebuildingPackInfo:t GetHousingRebuildingTaxInfo:t GetHousingUccInfo:t GetHousingUccItemInfo:t GetPrepayRequireItemInfo:t GetRequireItemInfoForRotate GetShipyardBaseProgress:n GetShipyardConstructionStepInfo:t GetShipyardOwnerName:s GetShipyardProtectionPeriod:n GetShipyardRemainProgress:n GetTaxItem:t GetTaxations IsCastle:b IsConvertTaxItemToAAPoint:b IsDominionCastle:b IsExpeditionHouse:b IsFreeDemolishHouse:b IsHouseRotatable:b IsHouseUnderConstruction:b IsMyHouse:b IsSiegePeriod:b IsWarmUpPeriod LeaveUccItem LookAheadRebuildHouse NextStepFromBuildCheck PrepayHouseTax PrevStepFromBuildCheck Preview PreviewRotateHouse RequestHousingRebuildingTaxInfo RequestLookAheadMode RotateHouse SetHouseAllowRecover SetHouseForSale SetHouseName SetHousePermission SetUccItemSlotFromPick StartRebuild UseApplyUccItem:b"),
        ["X2Dominion"] = B("CanUpdateSiegeSchedule:b ChangeDominionTaxRate GetCurDefenseSiegeParticipantCount:n GetCurOffenseSiegeParticipantCount:n GetCurPeriodEndDate:t GetCurPeriodRemainDate:t GetCurPeriodRemainDateByCurrentZone:t GetCurPeriodStartDate:t GetCurSiegePeriodName:s GetDominionOriginOwnerFactionName GetGuardTowerHp GetGuardTowerId:n GetMySiegeZoneGroupTypes:t GetNextPeriodEndDate:t GetNextPeriodRemainDate:t GetNextPeriodStartDate:t GetNextSiegePeriodName:s GetOwnerFaction:s GetOwnerFactionName:s GetPeaceTaxAAPoint:s GetPeaceTaxMoney:s GetRecommendLevelToZoneGroup GetReinforceRemainDate GetSiegeCurDeffenseExpeditionName:s GetSiegeCurOffenseExpeditionName:s GetSiegeInfoDominion GetSiegeMember:s GetSiegePeriodEndDate:t GetSiegePeriodName:s GetSiegePeriodStartDate:t GetSiegeProgressInfo:t GetSiegeRewardItem:t GetSiegeTimeInfo GetSiegeWinScore:t GetSiegeZoneGroup:n GetTaxRate:n GetZoneGroupName:s IsInSiegeTeam:b IsNextSiegePeriodToday:b IsNotOutlawOffensebyMyFaction:b IsOutlawOffensebyMyFaction:b IsReinforceArrived IsSiegeExpedition:b IsSiegeSecondHalf:b IsSiegeWinnerMyFaction:b"),
        ["X2Resident"] = B("FilterHousingTradeList:b FireNuonsArrow GetContributionRankReward:t GetHousingTradeRefreshTime:n GetResidentBoardContent:t GetResidentDesc GetResidentMembers GetResidentZoneList RefreshResidentMembers RequestHousingTradeList"),
        ["X2Indun"] = B("AskLeaveInstantGame GetIndunPlayingInfo:t GetRoundIndunActivation:b GetRoundInfo:t GetRoundLeftTime:n GetTimeLimitRound:b GetTotalRound:n IsEntranceIndunMatch:b IsNonRoundUiInstance:b SetInstanceGameDifficult:n"),
        ["X2BattleField"] = B("AskLeaveInstantGame CancelInstanceGame ClearBestRatingReward ClearInstantGameCancelInfo EndKillStreakSound GetApplyInstanceInfo:t GetBannerInfo:t GetBestRatingReward:t GetDetailInstanceInfo GetEndReasonInfo:t GetFactionInfo:t GetInstanceAvailableLevel:t GetInstanceListByKind:t GetInstanceName:s GetInstanceRewardMailInfo:t GetInstanceRoundResultMessageInfo GetInstanceUiKindList:t GetMemberInfo:t GetMyKillstreakSkillsInfos:t GetMyPickBuffInfos:t GetProgressEntireInfo:t GetProgressRankInfo:t GetProgressScoreInfo:t GetProgressTargetNpcInfo:t GetProgressTimeInfo:t GetProgressVictoryConditionInfo:t GetRewardInfo:t GetScoreColumnInfo:t GetTargetNpcInfo:t GetVersusFactionInfo:t GetVictoryInfo:t IsApplyInstance:b IsInGlobalField:b IsInInstantGame:b IsPossiblePickBuff:b OffBanner PickBuff RequestCancelReentry RequestInstanceGame RequestLeaveUserList RequestTryReentry RequestTryReentryCheck ToggleBattleField"),
        ["X2Instance"] = B("GetInstanceSummaryInfo:t GetPointInfo:t"),
        ["X2SiegeWeapon"] = B("CanExchangeSlaveEquipment:b CanRepairEquipSlot:b CanSlaveEquipPickedItem:b GetMountedSiegeWeaponInfo:t GetShipInfo:t GetSiegeWeaponSpeed:n GetSiegeWeaponTurnSpeed:n GetSlaveCustomizingType:n GetSlaveEquipSlotInfo:t GetSlaveEquipSlotUIInfo:t GetVehicleInfo:t IsSlaveShip:b IsTargetMySiegeWeapon:b PickEquipSlotOfSlave SetSiegeWeaponName UninstallEquipSlotOfSlave"),
        ["X2Decal"] = B("CanMakeDirectionGuide:b CanMakeGuidedDecal:b DisableTargetDecal DisableTargetDecalLayer GetMaxDecalCount:n SetMinimunSizeTargetDecal SetQuestGuidDecalByIndex SetTargetDecalLoopAnimation SetTargetDecalMaterial SetTargetDecalStartAnimation"),
        ["X2Interaction"] = B("CancelNPCInteraction GetInteractionSkillIconPath:s")
    };
}
